### ISSUE TITLE
it do not work in sdwebui

### ISSUE THREAD

**Issue by aurorascy** [wkpark/uddetailer#104]

**Comment by idk3456789765** [comment]
having the same issue in forge. heres the error i get with uddetailer activated:
```
*** Error running postprocess_image: C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\webui\extensions\uddetailer\scripts\ddetailer.py
	Traceback (most recent call last):
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\webui\modules\scripts.py", line 940, in postprocess_image
    	script.postprocess_image(p, pp, *script_args)
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\webui\extensions\uddetailer\scripts\ddetailer.py", line 3442, in postprocess_image
    	self._postprocess_image(p, pp, use_prompt_edit, use_prompt_edit_2,
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\webui\extensions\uddetailer\scripts\ddetailer.py", line 3009, in _postprocess_image
    	results_a = inference(init_image, dd_model_a, dd_conf_a/100.0, label_a, dd_classes_a, dd_max_per_img_a)
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\webui\extensions\uddetailer\scripts\ddetailer.py", line 4037, in inference
    	results = mp_detector_face(image, modelname, conf_thres, label, classes, exclude_classes, max_per_img)
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\webui\extensions\uddetailer\scripts\detectors\mediapipe.py", line 31, in mediapipe_detector_face
    	results = face_detector.process(npimg)
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\system\python\lib\site-packages\mediapipe\python\solutions\face_detection.py", line 105, in process
    	return super().process(input_data={'image': image})
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\system\python\lib\site-packages\mediapipe\python\solution_base.py", line 351, in process
    	self._get_packet_content(self._output_stream_type_info[stream_name],
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\system\python\lib\site-packages\mediapipe\python\solution_base.py", line 595, in _get_packet_content
    	return getattr(packet_getter, 'get_' + packet_data_type.value)(
  	File "C:\Users\user\Desktop\desktop\ai\webui_forge_cu121_torch231\system\python\lib\site-packages\mediapipe\python\packet_getter.py", line 111, in get_proto_list
    	message_class = message_factory.GetMessageClass(descriptor)
	AttributeError: module 'google.protobuf.message_factory' has no attribute 'GetMessageClass'

---

```

the image still generates fine, it just doesnt utilize uddetailer at all.
