### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by AbramovS1** [wkpark/uddetailer#52]
I ask for help!
Error caught was: No module named 'triton'
H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\extensions\uddetailer.
*** Command: "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\Scripts\python.exe" "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\extensions\uddetailer\install.py"
Launching Web UI with arguments: --xformers --api --skip-python-version-check
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\extensions\uddetailer\install.py", line 110, in <module>
***     install()
***   File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\extensions\uddetailer\install.py", line 29, in install
***     mmdet_version = importlib.metadata.version("mmdet")
***   File "importlib\metadata\__init__.py", line 996, in version
***   File "importlib\metadata\__init__.py", line 969, in distribution
***   File "importlib\metadata\__init__.py", line 548, in from_name
*** importlib.metadata.PackageNotFoundError: No package metadata was found for mmdet
*** Error loading script: ddetailer.py
    Traceback (most recent call last):
      File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\extensions\uddetailer\scripts\ddetailer.py", line 20, in <module>
        from scripts.mediapipe import mediapipe_detector_face as mp_detector_face
      File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\extensions\uddetailer\scripts\mediapipe.py", line 2, in <module>
        import mediapipe as mp
    ModuleNotFoundError: No module named 'mediapipe'

---
*** Error loading script: mediapipe.py
    Traceback (most recent call last):
      File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\extensions\uddetailer\scripts\mediapipe.py", line 2, in <module>
        import mediapipe as mp
    ModuleNotFoundError: No module named 'mediapipe'

---
Loading weights [59ffe2243a] from H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\models\Stable-diffusion\Chilloutmix-Ni-pruned-fp16-fix.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\configs\v1-inference.yaml
Startup time: 9.6s (prepare environment: 6.2s, other imports: 1.1s, load scripts: 1.1s, create ui: 0.5s, gradio launch: 0.4s, add APIs: 0.1s).
Applying attention optimization: xformers... done.
Model loaded in 2.9s (load weights from disk: 0.7s, create model: 0.8s, apply weights to model: 1.0s, calculate empty prompt: 0.2s).
Traceback (most recent call last):
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\ui_extra_networks.py", line 392, in pages_html
    return refresh()
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\ui_extra_networks.py", line 400, in refresh
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\ui_extra_networks.py", line 400, in <listcomp>
    ui.pages_contents = [pg.create_html(ui.tabname) for pg in ui.stored_extra_pages]
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\ui_extra_networks.py", line 162, in create_html
    self.items = {x["name"]: x for x in self.list_items()}
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\ui_extra_networks.py", line 162, in <dictcomp>
    self.items = {x["name"]: x for x in self.list_items()}
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\ui_extra_networks_checkpoints.py", line 35, in list_items
    yield self.create_item(name, index)
  File "H:\Stable Diffusionv2(NO REMOVE)\Packages\Stable Diffusion Web UI\modules\ui_extra_networks_checkpoints.py", line 18, in create_item
    path, ext = os.path.splitext(checkpoint.filename)
AttributeError: 'NoneType' object has no attribute 'filename'

**Comment by wkpark** [comment]
Thank you for your reporting. fixed now
https://github.com/wkpark/uddetailer/pull/53
