### ISSUE TITLE
Extension doesn't show in web UI, traceback in the logs

### ISSUE THREAD

**Issue by guystreeter** [wkpark/uddetailer#63]
I have installed the extension through the Extension tab in SD web UI, but it does not show in the UI. This traceback occurs twice during startup:
```
*** Error calling: /data_dir/extensions/uddetailer/scripts/ddetailer.py/ui
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 489, in wrap_call
        return func(*args, **kwargs)
      File "/data_dir/extensions/uddetailer/scripts/ddetailer.py", line 807, in ui
        cn_module = get_controlnet_module()
      File "/data_dir/extensions/uddetailer/scripts/ddetailer.py", line 700, in get_controlnet_module
        cn_module.init_cn_module()
      File "/data_dir/extensions/uddetailer/cn_module.py", line 28, in init_cn_module
        external_code = importlib.import_module(f"extensions.{ext.name}.scripts.external_code", "external_code")
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'extensions.sd-webui-controlnet'
```

**Comment by guystreeter** [comment]
That change seems to resolve the issue. Thanks.
Is that module supposed to exist in my installation? Do I have something configured incorrectly?

**Comment by wkpark** [comment]
> That change seems to resolve the issue. Thanks. Is that module supposed to exist in my installation? Do I have something configured incorrectly?

you don't have to install "ControlNet" extension. thank you for your feedback!
