### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by HinaHyugaHime** [wkpark/uddetailer#84]
```Model loaded in 1.7s (create model: 0.4s, apply weights to model: 0.5s, apply dtype to VAE: 0.2s, load VAE: 0.3s, calculate empty prompt: 0.3s).
*** Error executing callback before_ui for /home/hina/stable-diffusion-webui/extensions/uddetailer/scripts/ddetailer.py
    Traceback (most recent call last):
      File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/usr/lib/python3.11/http/client.py", line 1298, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/usr/lib/python3.11/http/client.py", line 1344, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output
        self.send(msg)
      File "/usr/lib/python3.11/http/client.py", line 990, in send
        self.connect()
      File "/usr/lib/python3.11/http/client.py", line 1463, in connect
        super().connect()
      File "/usr/lib/python3.11/http/client.py", line 956, in connect
        self.sock = self._create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/socket.py", line 827, in create_connection
        for res in getaddrinfo(host, port, 0, SOCK_STREAM):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    socket.gaierror: [Errno -3] Temporary failure in name resolution

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/hina/stable-diffusion-webui/modules/script_callbacks.py", line 397, in before_ui_callback
        c.callback()
      File "/home/hina/stable-diffusion-webui/extensions/uddetailer/scripts/ddetailer.py", line 336, in startup
        load_file_from_url(
      File "/home/hina/stable-diffusion-webui/extensions/uddetailer/scripts/ddetailer.py", line 68, in load_file_from_url
        download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
      File "/home/hina/stable-diffusion-webui/venv/lib/python3.11/site-packages/torch/hub.py", line 620, in download_url_to_file
        u = urlopen(req)
            ^^^^^^^^^^^^
      File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/urllib/request.py", line 519, in open
        response = self._open(req, data)
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
        result = func(*args)
                 ^^^^^^^^^^^
      File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

---```

**Comment by wkpark** [comment]
it seems temporal issue: `Temporary failure in name resolution`
