### ISSUE TITLE
Compatibility problem

### ISSUE THREAD

**Issue by nemesis2k7** [wkpark/uddetailer#88]
When using [LoRa Control - Dynamic Weights Controller](https://github.com/cheald/sd-webui-loractl) the detailer stops working completely giving this error

> *** Error running postprocess_image: H:\stable-diffusion-webui\extensions\uddetailer\scripts\ddetailer.py00,  2.21s/it]
    Traceback (most recent call last):
      File "H:\stable-diffusion-webui\modules\scripts.py", line 897, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "H:\stable-diffusion-webui\extensions\uddetailer\scripts\ddetailer.py", line 3360, in postprocess_image
        self._postprocess_image(p, pp, use_prompt_edit, use_prompt_edit_2,
      File "H:\stable-diffusion-webui\extensions\uddetailer\scripts\ddetailer.py", line 2704, in _postprocess_image
        extra_params = ddetailer_extra_params(
      File "H:\stable-diffusion-webui\extensions\uddetailer\scripts\ddetailer.py", line 532, in ddetailer_extra_params
        cn_params = cn_module.get_cn_extra_params(dd_states)
      File "H:\stable-diffusion-webui\extensions\uddetailer\cn_module.py", line 203, in get_cn_extra_params
        control_mode = external_code.control_mode_from_value(control_mode)
    AttributeError: module 'scripts.external_code' has no attribute 'control_mode_from_value'

Let me know if further information is needed.

**Comment by wkpark** [comment]
`AttributeError: module 'scripts.external_code' has no attribute 'control_mode_from_value'`

`cn_module.py` is a controlnet detector used by uddetailer, and this is a controlnet module error.
recent update of the controlnet remove their `control_mode_from_value()` routine

thank you for your report!

**Comment by wkpark** [comment]
fixed by commit https://github.com/wkpark/uddetailer/commit/cc42c5e0736329ec74bf7e349555404e7d01b981
