### ISSUE TITLE
install uddetailer into new version of Forge it destroys it all

### ISSUE THREAD

**Issue by jil49300** [wkpark/uddetailer#96]
Hello everyone,
In my experience, uDetailer is an essential tool, even more so than aDetailer.
However, there's a major issue...
Every time I install this extension:
https://github.com/wkpark/uddetailer, it completely breaks the new version of Forge, rendering it unusable.

When I install directly from https://github.com/wkpark/uddetailer, it turns in circle without doing anything.
The python windows shows this message :
" Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False} "

After relauching, Forge is dead, Python is showing this message :

" Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-313-g8a042934
Commit hash: https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/8a04293430af3b80760aa0065219256ce0bccc34
Installing requirements "

thanks by advance for your help becoz ...
uDetailer rocks big time !!! 😛🥰🥰🥰

**Comment by wkpark** [comment]
i can confirm that uddetailer works fine with the latest forge.
(some features of uddetailer will not work - Inpainting Helper does not work with the forge)

**Comment by Hertzila** [comment]
I think I have the same issue. Simply put, trying to install uDetailer makes Forge enter an infinite loop while installing requirements. Both the Extensions tab and manually installing cause the loop, installing from the tab causes Forge to hang, while manually installing causes Forge to never actually start its interface. No error messages or such are printed, so it doesn't visibly fail, but *something* is failing to resolve and Forge becomes stuck in this loop.

**Comment by wkpark** [comment]
ok. I will check it asap. thanks for reporting

**Comment by wkpark** [comment]
newly found bug fixed at https://github.com/wkpark/uddetailer/pull/100
and some scheduler bug fixed by https://github.com/wkpark/uddetailer/commit/e9e94101ed06bfa60a4efac0200959897ae7699e

without these bugs, forge just just loaded without an issue under the follow setting:
- `torch 2.1.2+cu121`
- `Python 3.10.12`
- `torch==2.3.1` also tested using `--reinstall-torch` arg

<details>

~~~
venv "D:\src\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:34:57) [MSC v.1936 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-555-g1d3f73b7
Commit hash: 1d3f73b78dd595729f41e8405072eb34a7ad9232
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch==2.3.1
  Downloading https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-win_amd64.whl (2423.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 GB 12.5 MB/s eta 0:00:00
Collecting torchvision==0.18.1
  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.18.1%2Bcu121-cp310-cp310-win_amd64.whl (5.7 MB)
Requirement already satisfied: filelock in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from torch==2.3.1) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from torch==2.3.1) (4.9.0)
Requirement already satisfied: sympy in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from torch==2.3.1) (1.12)
Requirement already satisfied: networkx in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from torch==2.3.1) (3.2.1)
Requirement already satisfied: jinja2 in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from torch==2.3.1) (3.1.3)
Requirement already satisfied: fsspec in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from torch==2.3.1) (2024.2.0)
Collecting mkl<=2021.4.0,>=2021.1.1 (from torch==2.3.1)
  Downloading https://download.pytorch.org/whl/mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.5/228.5 MB 51.4 MB/s eta 0:00:00
Requirement already satisfied: numpy in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from torchvision==0.18.1) (1.26.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from torchvision==0.18.1) (9.5.0)
Collecting intel-openmp==2021.* (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1)
  Downloading https://download.pytorch.org/whl/intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 41.7 MB/s eta 0:00:00
Collecting tbb==2021.* (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1)
  Downloading tbb-2021.13.1-py3-none-win_amd64.whl.metadata (1.1 kB)
Requirement already satisfied: MarkupSafe>=2.0 in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from jinja2->torch==2.3.1) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in d:\src\stable-diffusion-webui-forge\venv\lib\site-packages (from sympy->torch==2.3.1) (1.3.0)
Downloading tbb-2021.13.1-py3-none-win_amd64.whl (286 kB)
Installing collected packages: tbb, intel-openmp, mkl, torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 2.1.2+cu121
    Uninstalling torch-2.1.2+cu121:
      Successfully uninstalled torch-2.1.2+cu121
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.16.2+cu121
    Uninstalling torchvision-0.16.2+cu121:
      Successfully uninstalled torchvision-0.16.2+cu121
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.23.post1 requires torch==2.1.2, but you have torch 2.3.1+cu121 which is incompatible.
Successfully installed intel-openmp-2021.4.0 mkl-2021.4.0 tbb-2021.13.1 torch-2.3.1+cu121 torchvision-0.18.1+cu121
Launching Web UI with arguments: --listen --port 7870 --xformers --theme dark --enable-insecure-extension-access --reinstall-torch
Total VRAM 16380 MB, total RAM 63413 MB
pytorch version: 2.3.1+cu121
WARNING:xformers:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.3.1+cu121)
    Python  3.10.11 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: f:/webui/webui/stable-diffusion-webui\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.1.2, num models: 9
Loading additional modules ... done.
ERROR - failed to import mmcv - No module named 'mmcv'
 Total 42 mmdet, 0 yolo and 3 mediapipe models.
 You can enable validity tester in the Settings-> μ DDetailer.
loading.. cn_modole
 - ControlNet extension sd_forge_controlnet found: lib_controlnet.external_code
 - default µ DDetailer model= face_yolov8n.pth [882ebbb6]
 - default µ DDetailer model= face_yolov8n.pth [882ebbb6]
2024-10-07 21:53:02,902 - ControlNet - INFO - ControlNet UI callback registered.
D:\src\stable-diffusion-webui-forge\extensions\sd-webui-pnginfo-diff\scripts\pnginfo_diff.py:243: GradioDeprecationWarning: unexpected argument for CheckboxGroup: multiselect
  param1 =  gr.CheckboxGroup(label="Extra params", choices=[], value=[], multiselect=True)
D:\src\stable-diffusion-webui-forge\extensions\sd-webui-pnginfo-diff\scripts\pnginfo_diff.py:269: GradioDeprecationWarning: unexpected argument for CheckboxGroup: multiselect
  param2 =  gr.CheckboxGroup(label="Extra params", choices=[], value=[], multiselect=True)
Model selected: {'checkpoint_info': {'filename': 'f:\\webui\\webui\\stable-diffusion-webui\\models\\Stable-diffusion\\fluxasiandoll_checkpointV10ClipvaeY.safetensors', 'hash': '3026b670'}, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://0.0.0.0:7870

To create a public link, set `share=True` in `launch()`.
Startup time: 245.0s (initial startup: 0.071s, prepare environment: 170.171s, import torch: 26.398s, initialize shared: 0.455s, other imports: 1.286s, setup gfpgan: 0.036s, list extensions: 0.025s, list SD models: 0.084s, load scripts: 9.238s, load upscalers: 0.015s, refresh VAE: 0.017s, initialize google blockly: 12.332s, scripts before_ui_callback: 5.163s, create ui: 8.880s, gradio launch: 9.411s, add APIs: 0.019s, app_started_callback: 1.480s).
Loading Model: {'checkpoint_info': {'filename': 'f:\\webui\\webui\\stable-diffusion-webui\\models\\Stable-diffusion\\fluxasiandoll_checkpointV10ClipvaeY.safetensors', 'hash': '3026b670'}, 'additional_modules': [], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'transformer': 780, 'vae': 244, 'text_encoder': 198, 'text_encoder_2': 220, 'ignore': 0}
XXXX device = cpu , dtype = torch.float16
Using Detected T5 Data Type: torch.float8_e4m3fn
XXXX device = cpu , dtype = torch.float8_e4m3fn
Using Detected UNet Type: torch.float8_e4m3fn
XXXX device = cpu , dtype = torch.float8_e4m3fn
XXXX device = cpu , dtype = torch.bfloat16
Working with z of shape (1, 16, 32, 32) = 16384 dimensions.
K-Model Created: {'storage_dtype': torch.float8_e4m3fn, 'computation_dtype': torch.bfloat16}
Model loaded in 1.6s (unload existing model: 0.470s, forge model load: 1.167s).
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
[Unload] Trying to free 7725.00 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 15213.00 MB, Model Require: 5154.62 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 9034.38 MB, All loaded to GPU.
Moving model(s) has taken 4.62 seconds
Distilled CFG Scale: 3.5
[Unload] Trying to free 15861.01 MB for cuda:0 with 0 models keep loaded ... Current free memory is 9932.57 MB ... Unload model JointTextEncoder Done.
[Memory Management] Target: KModel, Free GPU: 15167.17 MB, Model Require: 11350.07 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 2793.11 MB, All loaded to GPU.
Moving model(s) has taken 11.96 seconds
XXXX <<< x.dtype =  torch.float32
  0%|                                                                                                                                                                | 0/6 [00:00<?, ?it/s]XXXX x.dtype =  torch.float32
done in 0.6s (step 1: 0.060s, step 2: 0.049s, double: 0.232s, single: 0.218s)
 17%|#########################3                                                                                                                              | 1/6 [00:00<00:02,  1.69it/s]XXXX x.dtype =  torch.float32                                                                                                                                         | 0/6 [00:00<?, ?it/s]
done in 0.2s (double: 0.085s, single: 0.103s)
 33%|##################################################6                                                                                                     | 2/6 [00:02<00:05,  1.39s/it]XXXX x.dtype =  torch.float32██████████████████████████████████████▎                                                                                          | 2/6 [00:01<00:03,  1.02it/s]
done in 0.2s (double: 0.088s, single: 0.112s)
 50%|############################################################################                                                                            | 3/6 [00:04<00:05,  1.67s/it]XXXX x.dtype =  torch.float32█████████████████████████████████████████████████████████████                                                                    | 3/6 [00:03<00:04,  1.40s/it]
done in 0.2s (double: 0.101s, single: 0.093s)
 67%|#####################################################################################################3                                                  | 4/6 [00:06<00:03,  1.80s/it]XXXX x.dtype =  torch.float32███████████████████████████████████████████████████████████████████████████████████▋                                             | 4/6 [00:05<00:03,  1.62s/it]
done in 0.2s (double: 0.107s, single: 0.105s)
 83%|##############################################################################################################################6                         | 5/6 [00:08<00:01,  1.87s/it]XXXX x.dtype =  torch.float32██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 5/6 [00:07<00:01,  1.76s/it]
done in 0.2s (step 2: 0.011s, double: 0.087s, single: 0.113s)
100%|########################################################################################################################################################| 6/6 [00:10<00:00,  1.76s/it]
[Unload] Trying to free 3883.21 MB for cuda:0 with 0 models keep loaded ... Current free memory is 3642.20 MB ... Unload model KModel Done.██████████████████| 6/6 [00:09<00:00,  1.83s/it]
[Memory Management] Target: IntegratedAutoencoderKL, Free GPU: 15143.36 MB, Model Require: 159.87 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 13959.49 MB, All loaded to GPU.
Moving model(s) has taken 9.71 seconds

0: 640x448 1 face, 171.0ms
Speed: 9.0ms preprocess, 171.0ms inference, 38.0ms postprocess per image at shape (1, 3, 640, 448)
Total 1 was detected by model A...
Processing 1 detection of model A for output generation 1.
[Unload] Trying to free 2981.81 MB for cuda:0 with 1 models keep loaded ... Current free memory is 14906.80 MB ... Done.
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
[Unload] Trying to free 7819.24 MB for cuda:0 with 0 models keep loaded ... Current free memory is 14925.91 MB ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 14925.91 MB, Model Require: 5227.11 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 8674.80 MB, All loaded to GPU.
Moving model(s) has taken 2.08 seconds
Distilled CFG Scale: 3.5
[Unload] Trying to free 15861.03 MB for cuda:0 with 0 models keep loaded ... Current free memory is 9684.95 MB ... Unload model IntegratedAutoencoderKL Current free memory is 9846.46 MB ... Unload model JointTextEncoder Done.
[Memory Management] Target: KModel, Free GPU: 15082.57 MB, Model Require: 11350.09 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 2708.48 MB, All loaded to GPU.
Moving model(s) has taken 7.93 seconds
XXXX <<< x.dtype =  torch.float32
  0%|                                                                                                                                                                | 0/3 [00:00<?, ?it/s]XXXX x.dtype =  torch.float32
done in 0.3s (double: 0.133s, single: 0.148s)
 33%|##################################################6                                                                                                     | 1/3 [00:00<00:00,  3.24it/s]XXXX x.dtype =  torch.float32██████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 7/9 [00:34<00:18,  9.27s/it]
done in 0.2s (double: 0.085s, single: 0.111s)
 67%|#####################################################################################################3                                                  | 2/3 [00:02<00:01,  1.25s/it]XXXX x.dtype =  torch.float32█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 8/9 [00:36<00:06,  6.95s/it]
done in 0.2s (double: 0.108s, single: 0.090s)
100%|########################################################################################################################################################| 3/3 [00:04<00:00,  1.40s/it]
[Unload] Trying to free 3883.21 MB for cuda:0 with 0 models keep loaded ... Current free memory is 3577.88 MB ... Unload model KModel Done.██████████████████| 9/9 [00:38<00:00,  5.41s/it]
[Memory Management] Target: IntegratedAutoencoderKL, Free GPU: 15080.04 MB, Model Require: 159.87 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 13896.16 MB, All loaded to GPU.
Moving model(s) has taken 7.10 seconds
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:49<00:00,  5.46s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:49<00:00,  5.41s/it]
~~~

</details>

**Comment by Hertzila** [comment]
python: ``3.10.6``
torch: ``2.3.1+cu121``

How long is a fresh install into a fresh Forge install supposed to take? Simply downloading the recommended one from [here](https://github.com/lllyasviel/stable-diffusion-webui-forge?tab=readme-ov-file#installing-forge), updating it and trying to install uDetailer there through the Extensions tab has taken full 15 minutes with no outward signs of progressing. No logs, no notes about what's happening or warnings about long installs, nothing.

Every other extension I've seen has taken at most like 30 seconds to install, so my first thought is that it's gotten stuck in an infinite loop.

Is uDetailer supposed to take long? What's it doing? Maybe consider printing some logs onto the command shell about the progress?

**Comment by wkpark** [comment]
> python: `3.10.6` torch: `2.3.1+cu121`
> 
> How long is a fresh install into a fresh Forge install supposed to take? Simply downloading the recommended one from [here](https://github.com/lllyasviel/stable-diffusion-webui-forge?tab=readme-ov-file#installing-forge), updating it and trying to install uDetailer there through the Extensions tab has taken full 15 minutes with no outward signs of progressing. No logs, no notes about what's happening or warnings about long installs, nothing.
> 
> Every other extension I've seen has taken at most like 30 seconds to install, so my first thought is that it's gotten stuck in an infinite loop.
> 
> Is uDetailer supposed to take long? What's it doing? Maybe consider printing some logs onto the command shell about the progress?

as you can see above log, it started around ~250sec (in this case, it was try to install torch 2.3.1 + its dependencies)

so strange...

I've just uninstall all udetailer depends packages manually and  started webui-user.bat again.
(uninstall ultralytics, mediapipe, mmdet, openmim, mmcv, mmengine...)
in this case, it automatically install ultraytics, mediapipe... and started within 92sec. ~15 minutes way too long..

**Comment by master131** [comment]
Installing the `ninja` package into the environment significantly speeds up the compile time for mmcv. Without it, it was only doing a single threaded build and hardly utilising my CPU.

**Comment by Hertzila** [comment]
Looking over the logs, it looks like mmcv or mmdet is the culprit. It first tries to compile wheels for around half an hour, then exits with an error from the compiler and quits the whole process. Restarting the Forge WebUI restarts the process. Manual attempts have the same result.

```
*** Traceback (most recent call last):
***   File "D:\Utilities\Forge-SD-TestCase\webui\extensions\uddetailer\install.py", line 184, in <module>
***     install()
***   File "D:\Utilities\Forge-SD-TestCase\webui\extensions\uddetailer\install.py", line 77, in install
***     run(f'"{python}" -m mim install -U mmdet>=3.0.0', desc="Installing mmdet", errdesc="Couldn't install mmdet")
***   File "D:\Utilities\Forge-SD-TestCase\webui\modules\launch_utils.py", line 125, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install mmdet.
*** Command: "D:\Utilities\Forge-SD-TestCase\system\python\python.exe" -m mim install -U mmdet>=3.0.0
*** Error code: 1
*** stderr:   error: subprocess-exited-with-error
***
***   python setup.py bdist_wheel did not run successfully.
***   exit code: 1
***
***   [1024 lines of output]


*...Long list of installation commands...*


***   pybind.cpp
***   D:\Utilities\Forge-SD-TestCase\system\python\lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
***   error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
***   [end of output]
***
***   note: This error originates from a subprocess, and is likely not a problem with pip.
***   ERROR: Failed building wheel for mmcv
*** ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects
```

So I suppose, any chance for a uDDetailer version which hard-disables the installation attempts on those parts and just defaults to the alternates (ultralytics + mediapipe)?

----

Note on venv, by default, Forge doesn't seem to use it. The default installation uses some commands in ``environment.bat`` for what I'm guessing is the same effect, but the default venv process does not exist. Eg. there's no ``venv\scripts\activate`` to run. Instead, you start a command prompt, run the ``environment.bat`` and then run commands with ``python.exe -m <command>`` for things like ``pip`` to work.

**Comment by Infiexe** [comment]
Same here. Installing extension through Forge creates the folder but it's not available in the extensions tab. After restarting, Forge hangs during the installing requirements step. I'm on 5070 Ti so I'm using newest Torch etc.

**Comment by angelika3377** [comment]
doesn't work also on 5060 ti
