### ISSUE TITLE
mmcv 2.2.0 and mmengine 0.10.4 may not work

### ISSUE THREAD

**Issue by EPYC7773X** [wkpark/uddetailer#97]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Check mmcv version...
Your mmcv version 2.2.0 may not work with mmyolo.
or you need to fix version restriction of __init__.py of mmyolo manually, to use mmcv 2.1.0 with mmyolo.
Check mmengine version...
Your mmengine version 0.10.4 may not work on windows...
Please install mmengine 0.8.5 manually or install latest bitsandbytes >= 0.43.0 or un-official patched version of bitsandbytes-windows.
Launching Web UI with arguments: --xformers --xformers-flash-attention --opt-channelslast --enable-insecure-extension-access
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
Loading weights [a4398235c9] from E:\WebUI\Automatic1100\stable-diffusion-webui\models\Stable-diffusion\remasterizexl_v10.safetensors
Creating model from config: E:\WebUI\Automatic1100\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
E:\WebUI\Automatic1100\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Warning - ultralytics for yolov8 is not available.
ERROR - failed to import mmyolo - MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
*** Error executing callback before_ui for E:\WebUI\Automatic1100\stable-diffusion-webui\extensions\uddetailer\scripts\ddetailer.py
    Traceback (most recent call last):
      File "E:\WebUI\Automatic1100\stable-diffusion-webui\modules\script_callbacks.py", line 397, in before_ui_callback
        c.callback()
      File "E:\WebUI\Automatic1100\stable-diffusion-webui\extensions\uddetailer\scripts\ddetailer.py", line 367, in startup
        inference_detector, init_detector, get_classes, Config = get_dependency_modules()
      File "E:\WebUI\Automatic1100\stable-diffusion-webui\extensions\uddetailer\scripts\ddetailer.py", line 120, in get_dependency_modules
        from mmdet.core import get_classes
      File "E:\WebUI\Automatic1100\stable-diffusion-webui\venv\lib\site-packages\mmdet\__init__.py", line 17, in <module>
        and mmcv_version < digit_version(mmcv_maximum_version)), \
    AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

---
loading.. cn_modole
 - default µ DDetailer model= bbox/mmdet_anime-face_yolov3.pth [38208bb6]
 - default µ DDetailer model= bbox/mmdet_anime-face_yolov3.pth [38208bb6]
 
 
 
 Got a Error message with this.
 I actually downloaded dddetailer right before, and I removed it from extension folder since its not compatible in 1.10.1 version, so I installed uddetailer but this thing got wrong from version issue.
 How can I fix it?

**Comment by EPYC7773X** [comment]
ERROR - failed to import mmcv - No module named 'mmcv'
Warning - ultralytics for yolov8 is not available.
 Total 0 mmdet, 0 yolo and 3 mediapipe models.
 Total 0 valid mmdet configs are found.
 You can disable validity tester in the Settings-> μ DDetailer.
Check config files...
Done
loading.. cn_modole
 - default µ DDetailer model= mediapipe_face_short
 - default µ DDetailer model= mediapipe_face_short
 
 Downgraded with pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html and successfully installed mmcv, but still it cannot import mmcv module.
 No idea what is happening...

**Comment by EPYC7773X** [comment]
Tried clean reinstall

*** Error running install.py for extension E:\WebUI\Automatic1100\stable-diffusion-webui\extensions\uddetailer.
*** Command: "E:\WebUI\Automatic1100\stable-diffusion-webui\venv\Scripts\python.exe" "E:\WebUI\Automatic1100\stable-diffusion-webui\extensions\uddetailer\install.py"
*** Error code: 1
*** stdout: Installing openmim
*** Installing None
*** Installing None
***
*** stderr: Traceback (most recent call last):
***   File "E:\WebUI\Automatic1100\stable-diffusion-webui\extensions\uddetailer\install.py", line 135, in <module>
***     install()
***   File "E:\WebUI\Automatic1100\stable-diffusion-webui\extensions\uddetailer\install.py", line 39, in install
***     run_pip(f'install mediapipe>=0.10.3')
***   File "E:\WebUI\Automatic1100\stable-diffusion-webui\modules\launch_utils.py", line 144, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "E:\WebUI\Automatic1100\stable-diffusion-webui\modules\launch_utils.py", line 116, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install None.
*** Command: "E:\WebUI\Automatic1100\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install mediapipe>=0.10.3 --prefer-binary
*** Error code: 1
*** stderr: ERROR: Could not install packages due to an OSError: [WinError 5] \u05fc \u017a\u01fe\u03f4: 'E:\\WebUI\\Automatic1100\\stable-diffusion-webui\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
*** Check the permissions.
***
***

And got this, in Automatic1111 WebUI 1.10.0 version.

**Comment by wkpark** [comment]
Please see.
https://github.com/wkpark/uddetailer/wiki/Required-python-packages#use-mmdet-with-torch-220cu121

-----
- [ ] open `cmd` window prompt. and change to the `E:\WebUI\Automatic100\stable-diffusion-webui`  folder. (with `cd` command)
- [ ] activate `venv` environment first (please see above manual) (run `venv\scripts\activate` in the cmd prompt)
- [ ] check `mmcv` package using `pip show mmcv` commend under venv environment. 
- [ ] please see above wiki manual for details.

**Comment by wkpark** [comment]
ok. I've update my environment with pytorch v2.2.x and found that pytorch v2.2.x need to install mmcv 2.2.0 with some minor modification of `mmyolo/__init__.py` and `mmdet/__init__.py`
this issue will be solved by PR #101

thanks for your reporting!
